# Generated by Django 2.2.28 on 2023-03-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0003_auto_20230312_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='id',
        ),
        migrations.AddField(
            model_name='kit',
            name='maintenance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
