# Generated by Django 2.2.28 on 2023-02-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0004_adminprofile_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
