# Generated by Django 2.2.28 on 2023-02-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0005_delete_adminprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='image',
        ),
    ]
