# Generated by Django 2.2.28 on 2023-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0005_auto_20230320_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
