# Generated by Django 2.2.28 on 2023-03-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0007_auto_20230323_1721'),
        ('canoe_club', '0007_remove_kit_image'),
    ]

    operations = [
    ]
