# Generated by Django 2.2.28 on 2023-02-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0008_page_social_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='location',
            field=models.CharField(default='oran mor', max_length=128),
            preserve_default=False,
        ),
    ]
