# Generated by Django 2.2.28 on 2023-03-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0008_merge_20230323_1838'),
        ('canoe_club', '0007_auto_20230323_1604'),
    ]

    operations = [
    ]
