# Generated by Django 2.2.28 on 2023-03-03 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0009_social_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('size', models.IntegerField(default=0)),
                ('colour', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('maintenance_problem', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='member',
        ),
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Member')]),
        ),
        migrations.AddField(
            model_name='kit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
