# Generated by Django 2.2.28 on 2023-03-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0010_auto_20230323_2119'),
        ('canoe_club', '0010_auto_20230324_1334'),
    ]

    operations = [
    ]
