# Generated by Django 2.2.28 on 2023-03-07 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0011_auto_20230307_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='kit',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='kit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kit',
            name='slug',
            field=models.SlugField(),
        ),
    ]
