# Generated by Django 2.2.28 on 2023-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0012_auto_20230307_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=True, verbose_name='is member'),
        ),
    ]
