# Generated by Django 2.2.28 on 2023-03-08 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0013_auto_20230307_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='oh_bo', unique=True),
            preserve_default=False,
        ),
    ]
