# Generated by Django 2.2.28 on 2023-03-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0014_auto_20230308_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='members',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
