# Generated by Django 2.2.28 on 2023-03-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0002_auto_20230309_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, upload_to='kit_images'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='maintenance_problem',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='size',
            field=models.IntegerField(),
        ),
    ]
