# Generated by Django 2.2.28 on 2023-03-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0006_social_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(to='canoe_club.UserProfile'),
        ),
    ]
