# Generated by Django 2.2.28 on 2023-03-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0006_social_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='image',
        ),
    ]
