# Generated by Django 2.2.28 on 2023-03-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canoe_club', '0009_merge_20230323_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canoe_club.UserProfile'),
        ),
    ]
